platform :ios, '6.1'

pod 'Facebook-iOS-SDK', '>=3.2.0'
pod 'CocoaLumberjack', '>=1.6'
pod 'AFNetworking', '>=1.1.0'
pod 'AFOAuth2Client', '>=0.1.0'

target :'AuthKit-ExampleTests', :exclusive => true do
  pod 'OCMock', '>= 2.0.1'
end