platform :ios, '6.1'

pod 'Facebook-iOS-SDK', '>=3.2.1'
pod 'CocoaLumberjack', :local => '~/Git/CocoaLumberjack'
pod 'AFNetworking', '>=1.1.0'
pod 'AFOAuth2Client', '>=0.1.0'
pod 'gtm-oauth2', '>=0.0.1'

target :'AuthKit-ExampleTests', :exclusive => true do
  pod 'OCMock', '>= 2.0.1'
end